version: "3.8"
services:
    proxy:
        container_name: proxy
        image: nginx:1.19.10-alpine
        ports:
          - 80:80
          - 443:443
        volumes:
          - ~/./proxy/conf/nginx.conf:/etc/nginx/nginx.conf
          - ~/./proxy/certs:/etc/nginx/certs
        depends_on:
            rabbitmq:
                condition: service_healthy           
        networks:
          - greentech_net           
    apigateway:
        container_name: apigateway
        hostname: apigateway
        image: domih/greentechmanager.apigateway
        build: 
            dockerfile: 'src/greentechmanager.apigateway/dockerfile'
        depends_on:
            rabbitmq:
                condition: service_healthy             
        healthcheck:
              test:  curl -f http://apigateway || exit 1
              interval: 5s
              retries: 5
              start_period: 5s
              timeout: 5s                
        networks:
           - greentech_net       
    identitysrv:
        container_name: identitysrv
        hostname: identitysrv
        image: domih/greentechmanager.identity
        build: 
            dockerfile: 'src/GreenTechManager.Identity/Dockerfile'
        depends_on:
            rabbitmq:
                condition: service_healthy                
        networks:
        - greentech_net
    operatorsrv:
        container_name: operatorsrv
        hostname: operatorsrv
        image: domih/greentechmanager.operators
        build: 
            dockerfile: 'src/GreenTechManager.Operators/Dockerfile'
        depends_on:
            rabbitmq:
                condition: service_healthy        
        networks:
        - greentech_net
    solarparksrv:
        container_name: solarparksrv
        hostname: solarparksrv
        image: domih/greentechmanager.solarparks
        build: 
            dockerfile: 'src/GreenTechManager.SolarParks/Dockerfile'
        depends_on:
            rabbitmq:
                condition: service_healthy         
        networks:
        - greentech_net
    windparksrv:
        container_name: windparksrv
        hostname: windparksrv
        image: domih/greentechmanager.windparks
        build: 
            dockerfile: 'src/GreenTechManager.WindParks/Dockerfile'
        depends_on:
            rabbitmq:
                condition: service_healthy       
        networks:
        - greentech_net
    rabbitmq:
        container_name: msgbrokersrv
        image: rabbitmq:3-management-alpine
        hostname: rabbitmq
        # ports:
            # - 5672:5672
            # - 15672:15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia
        healthcheck:
              test:  wget --no-verbose --tries=1 --spider http://localhost:15672 || exit 1
              interval: 5s
              retries: 5
              start_period: 5s
              timeout: 5s
        restart: unless-stopped                           
        networks:
            - greentech_net        
networks:
  greentech_net:
    name: greentech_net